### ISSUE TITLE
Why master branch has no scripts directory?

### ISSUE THREAD

**Issue by vickysongang** [Graylog2/graylog-project#14]
I found the scripts derectory in the pre-graylog-project-cli branch, but it is not in master branch, so how can I create a graylog web plugin based project?

**Comment by bernd** [comment]
@vickysongang Sorry for the inconvenience! We have to update our documentation to the new way of building plugins. Please track https://github.com/Graylog2/documentation/issues/391 for progress on this.

Thank you!
