### ISSUE TITLE
Bootstrapping the Graylog plugin skeleton from Github

### ISSUE THREAD

**Issue by ofentse001** [Graylog2/graylog-project#25]
I have Graylog 4.2.9 in production and I am busy writing a custom plugin for it. I used the below command to bootstrap

graylog-project.linux bootstrap github://Graylog2/graylog-project.git --manifest manifests/4.2.json

After bootstrapping, I get the full graylog-project 4.2.14-SNAPSHOT. I compiled and packaged everything and when I deploy in the production Graylog 4.2.9, the plugin fails to load. The below error is observed in the log files.

So when I try to load the plugin I built, it gives me the below error.
ERROR [CmdLineTool] Plugin “CustomAlert” requires version 4.2.14-SNAPSHOT - not loading!

How can I modify the manifests file so I can bootstrap the 4.2.9 branch (also without SNAPSHOP suffix)? By default at the moment the manifest bootstraps the latest branch.

**Comment by bernd** [comment]
@ofentse001 You can run `graylog-project exec "git checkout -f 4.2.9"` to check out the specific Graylog version in all Graylog repositories. When you run the package tasks now, you will get the correct dependency recorded in your plugin.

**Comment by ofentse001** [comment]
> graylog-project.linux bootstrap github://Graylog2/graylog-project.git --manifest manifests/4.2.json

Thank you @bernd. 
Do I initially run "graylog-project.linux bootstrap github://Graylog2/graylog-project.git --manifest manifests/4.2.json" before I then run the command you suggest? I directly ran the command you provided and I get the below.

graylog-project.linux exec "git checkout -f 4.2.9"
Unable to read manifest state from .graylog-project-manifest-state: open .graylog-project-manifest-state: no such file or directory

I actually went ahead and bootstrapped as I suggest using 4.2.json manifest file. Then I run git checkout -f 4.2.9 which changes the files to 4.2.9 as expected. However, it seems like not all the versions are changed correctly. I am now certain I am doing something wrong. What could be wrong with my approach?

**Comment by ofentse001** [comment]
Perhaps to be more accurate with my approach (instead of reporting my own experimental version), I bootstrapped normally. I then ran "graylog-project.linux exec "git checkout -f 4.2.9"" to checkout the 4.2.9 version. I have also updated the plugin pom as well.

When I do first compile, I then am told the child pom does not exist. Where did I go wrong? Or is there a step I need to add?

[graylog@graylog-dev graylog-project]$ mvn compile
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /home/graylog/build/graylog-project-repos/graylog2-server/../graylog-project-repos/graylog-plugin-sppp of /home/graylog/build/graylog-project-repos/graylog2-server/pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.graylog:graylog-parent:4.2.9 (/home/graylog/build/graylog-project-repos/graylog2-server/pom.xml) has 1 error
[ERROR]     Child module /home/graylog/build/graylog-project-repos/graylog2-server/../graylog-project-repos/graylog-plugin-smpp of /home/graylog/build/graylog-project-repos/graylog2-server/pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by ofentse001** [comment]
I need to be more accurate with my reporting and not report my own experimental procedure. I basically bootstrapped as stated above. But I then did the checkout of 4.2.9 as you suggest. But I then create the plugin archetypes and correct the plugin parent version to 4.2.9. Initial compile gave complaints to say the pom for plugin does not exist. I ran the checkout of 4.2.9 again and this resolved the issue. I then resumed compilation which came up with a runner error.

Looks like my graylog-project pom.xml has been overwritten as it no longer has my plugin module, and the version has reverted back to 4.2.0 instead of 4.2.9 :(

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] graylog-project 4.2.0 .............................. SUCCESS [  0.018 s]
[INFO] runner ............................................. FAILURE [ 36.929 s]
[INFO] Graylog Parent POM 4.2.9 ........................... SKIPPED
[INFO] Graylog Project Parent POM 4.2.9 ................... SKIPPED
[INFO] Graylog 4.2.9 ...................................... SKIPPED
[INFO] Graylog Plugin Parent POM 4.2.9 .................... SKIPPED
[INFO] graylog-storage-elasticsearch6 4.2.9 ............... SKIPPED
[INFO] graylog-storage-elasticsearch7 4.2.9 ............... SKIPPED
[INFO] full-backend-tests 4.2.9 ........................... SKIPPED
[INFO] Graylog Plugin with Web support Parent POM 4.2.9 ... SKIPPED
[INFO] graylog-plugin-archetype 4.2.9 ..................... SKIPPED
[INFO] Graylog Binary Distribution Tarball 4.2.9 .......... SKIPPED
[INFO] graylog-plugin-collector 4.2.9 ..................... SKIPPED
[INFO] graylog-plugin-aws 4.2.9 ........................... SKIPPED
[INFO] graylog-plugin-threatintel 4.2.9 ................... SKIPPED
[INFO] graylog-plugin-integrations 4.2.9 .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.460 s
[INFO] Finished at: 2023-01-14T19:06:18Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project runner: Could not resolve dependencies for project org.graylog:runner:jar:4.2.0: The following artifacts could not be resolved: org.graylog.plugins:graylog-plugin-collector:jar:4.2.0, org.graylog.plugins:graylog-plugin-aws:jar:4.2.0, org.graylog.plugins:graylog-plugin-threatintel:jar:4.2.0, org.graylog.plugins:graylog-plugin-integrations:jar:4.2.0: Could not find artifact org.graylog.plugins:graylog-plugin-collector:jar:4.2.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :runner

**Comment by ofentse001** [comment]
I managed to resolve this issue with a few steps.
a) git switch -c 4.2.9
b) modify graylog-project pom.xml and also pom.xml in runner folder, where version is 4.2.0 change to 4.2.9.
Then the compile process will compile without downloading the 4.2.0 pom.xml. It will work with 4.2.9.
