### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by bdruth** [Graylog2/graylog-project#29]
Is there a different way to bootstrap graylog development that's being maintained? The instructions at https://go2docs.graylog.org/current/what_more_can_graylog_do_for_me/plugins.html don't work beyond cloning projects. Even without creating a new plugin via the archetype, `mvn compile` fails because the `master` branch that's checked out of the various modules is expecting a 5.2.0-SNAPSHOT parent which isn't there ... 

* `mvn compile` fails by default
* no manifests exist beyond 4.2
* docker images don't work (similarly because `mvn compile` fails)
* IntelliJ IDEA fails similarly

I've tried manually updating pom references but it's been a decade and a half since I last wore my _POM guru_ badge and after getting a few levels deep it became apparent that nobody can actually be using this - at least, as it is in the current state of `master`.

My goal is simple: I'm using a graylog plugin that needs to have an import changed from the `javax` version of `@Inject` to the `jakarta` version so it's compatible (I hope) with 6.1 ... that _seemed_ like an easy task ...

What am I missing? Happy to be educated.

**Comment by bdruth** [comment]
Here's the `mvn compile` output:

❯ mvn compile
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.graylog.plugins:graylog-plugin-collector:5.2.0-SNAPSHOT: The following artifacts could not be resolved: org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT (absent): org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 26, column 13
[FATAL] Non-resolvable parent POM for org.graylog.plugins:graylog-plugin-aws:5.2.0-SNAPSHOT: The following artifacts could not be resolved: org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT (absent): Could not find artifact org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 26, column 13
[FATAL] Non-resolvable parent POM for org.graylog.plugins:graylog-plugin-threatintel:5.1.0-SNAPSHOT: The following artifacts could not be resolved: org.graylog.plugins:graylog-plugin-web-parent:pom:5.1.0-SNAPSHOT (absent): Could not find artifact org.graylog.plugins:graylog-plugin-web-parent:pom:5.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 26, column 13
[FATAL] Non-resolvable parent POM for org.graylog.plugins:graylog-plugin-integrations:5.2.0-SNAPSHOT: The following artifacts could not be resolved: org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT (absent): Could not find artifact org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 24, column 13
 @
[ERROR] The build could not read 4 projects -> [Help 1]
[ERROR]
[ERROR]   The project org.graylog.plugins:graylog-plugin-collector:5.2.0-SNAPSHOT (/Users/bruth/Projects/graylog-dev/graylog-project-repos/graylog-plugin-collector/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.graylog.plugins:graylog-plugin-collector:5.2.0-SNAPSHOT: The following artifacts could not be resolved: org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT (absent): org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 26, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.graylog.plugins:graylog-plugin-aws:5.2.0-SNAPSHOT (/Users/bruth/Projects/graylog-dev/graylog-project-repos/graylog-plugin-aws/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.graylog.plugins:graylog-plugin-aws:5.2.0-SNAPSHOT: The following artifacts could not be resolved: org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT (absent): Could not find artifact org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 26, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.graylog.plugins:graylog-plugin-threatintel:5.1.0-SNAPSHOT (/Users/bruth/Projects/graylog-dev/graylog-project-repos/graylog-plugin-threatintel/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.graylog.plugins:graylog-plugin-threatintel:5.1.0-SNAPSHOT: The following artifacts could not be resolved: org.graylog.plugins:graylog-plugin-web-parent:pom:5.1.0-SNAPSHOT (absent): Could not find artifact org.graylog.plugins:graylog-plugin-web-parent:pom:5.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 26, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.graylog.plugins:graylog-plugin-integrations:5.2.0-SNAPSHOT (/Users/bruth/Projects/graylog-dev/graylog-project-repos/graylog-plugin-integrations/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.graylog.plugins:graylog-plugin-integrations:5.2.0-SNAPSHOT: The following artifacts could not be resolved: org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT (absent): Could not find artifact org.graylog.plugins:graylog-plugin-web-parent:pom:5.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 24, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by bernd** [comment]
@bdruth I am working on bringing this repo up to reality in #30.
