### ISSUE TITLE
How to install CLI tool

### ISSUE THREAD

**Issue by debasish283** [Graylog2/graylog-project#6]
Documentation says  to download the latest binary and do like below cmd 
`$ mkdir -p $HOME/bin
$ cp graylog-project.linux $HOME/bin/graylog-project`
how it actually installs graylog-project 

I'm actually trying to run gralylog project using given steps  

`graylog-project bootstrap github://Graylog2/graylog-project.git` this graylog-project cmd tells command not found 
and what is bootstrap here

**Comment by mariussturm** [comment]
Hi,
you have to make it executable first. E,g. with `chmod +x $HOME/bin/graylog-project`. Afterwards you can get some help for each sub-command with `graylog-project -h`.

**Comment by debasish283** [comment]
even after running `chmod +x $HOME/bin/graylog-project` im not getting command 'graylog-project' any idea why it happens ??

**Comment by mariussturm** [comment]
Maybe the `$HOME/bin` folder is not in your PATH, either add it or use the full path to the binary `$HOME/bin/graylog-project -h`
